<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-AACR0J1" name="test_cases.Test_Browse_Data" tests="9" failures="1" timestamp="24 Feb 2016 20:13:33 GMT" time="23.268" errors="0">
  <testcase name="test_Logout" time="0.906" classname="test_cases.Test_Browse_Data"/>
  <testcase name="test_Select_Instrument" time="0.761" classname="test_cases.Test_Browse_Data"/>
  <testcase name="test_Download_CSV_File" time="1.951" classname="test_cases.Test_Browse_Data"/>
  <testcase name="test_close_Data_Viewer" time="0.087" classname="test_cases.Test_Browse_Data"/>
  <testcase name="test_Select_Survey_Response_Page" time="0.726" classname="test_cases.Test_Browse_Data">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at test_cases.AbstractTestCase.test_Select_Survey_Response_Page(AbstractTestCase.java:147)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
    </failure>
  </testcase> <!-- test_Select_Survey_Response_Page -->
  <testcase name="test_Login" time="1.778" classname="test_cases.Test_Browse_Data"/>
  <testcase name="test_Fill_Form_and_Launch_DataViewer" time="1.908" classname="test_cases.Test_Browse_Data"/>
  <testcase name="test_Data_Viewer_Functionality" time="3.253" classname="test_cases.Test_Browse_Data"/>
  <testcase name="test_Select_Project" time="11.898" classname="test_cases.Test_Browse_Data"/>
</testsuite> <!-- test_cases.Test_Browse_Data -->
